# netlify.toml

# Конфігурація для збірки
[build]
  command = "npm run build"  # Команда, яку Netlify має запустити для збірки
  publish = ".next"         # Папка, яку Next.js використовує для збірки

# Встановлення плагіну для Next.js
[plugins]
  package = "@netlify/plugin-nextjs"